# Generated by Django 4.0.6 on 2022-07-11 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('title', models.CharField(max_length=15000, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='categories/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('title', models.CharField(max_length=15000, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='recipes/', verbose_name='Картинка')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-title',),
            },
        ),
    ]
